# Generated by Django 3.1.3 on 2020-11-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20201123_0144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Pets',
        ),
    ]
